name: Monitoring list update
on: 
  repository_dispatch:
    types: [triggering event]
  push:

jobs:
  updating-websites-list:
    runs-on: 
    steps:
    #repo checkout
      - name: check-out the repo
        uses: actions/checkout@v3



    #environ and installing dependecies
      - name: Setup Conda Environment
        uses: AILAB-bh/gh-actions@setup-conda-env--1.0.0
      - name: install dependecies
      
      - name: activate conda env
        run: |
          source /opt/conda/etc/profile.d/conda.sh
          conda activate ${{ github.event.repository.name }}
          conda install -c conda-forge selenium
          sudo chmod +x geckodriver
      
      - name: running py script
        env:
           LOGIN: ${{ secrets.LOGIN }}
           PASSWORD: ${{ secrets.PASSWORD }}
        run: python automation.py
          
        