name: Monitoring list update
on: 
  repository_dispatch:
    types: [triggering event]
  push:

jobs:
  updating-websites-list:
    runs-on: windows-latest
    steps:
    #repo checkout
      - name: check-out the repo
        uses: actions/checkout@v3

    #installing dependecies
      - name: install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install selenium==4.5.0
      
      - name: running py script
        env:
          - LOGIN: ${{ secrets.LOGIN }}
          - PASSWORD: ${{ secrets.PASSWORD }}
        run: python automation.py
          
        