name: Monitoring list update
on: 
  repository_dispatch:
    types: [triggering event]
  push:

jobs:
  updating-websites-list:
    runs-on: ubuntu-latest
    steps:
    #repo checkout
      - name: check-out the repo
        uses: actions/checkout@v3
      - name: unzip webdriver
        run: tar -xzvf geckodriver-v0.32.0-linux64.tar.gz -C .
      - run: ls



    #installing dependecies
      - name: install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install selenium==4.5.0
      
      - name: running py script
        env:
           LOGIN: ${{ secrets.LOGIN }}
           PASSWORD: ${{ secrets.PASSWORD }}
        run: python automation.py
          
        